config/routes.rb
Rails.application.routes.draw do

  get 'auth/wyngle/callback', to: "sessions#auth_wyngle_callback"
  get 'auth/failure',         to: "sessions#auth_failure"
  controller :sessions do
    match '/sign_out', as: :sign_out, via: [:get, :delete], action: :sign_out
  end

  [:dashboard, :signed_in_default].each do |p|
    get 'dashboard', as: p, to: "dashboard#index"
  end
  get 'dashboard/settings', as: :settings,  to: "dashboard#settings"
  root 'welcome#index'

end

app/models/authentication/wyngle.rb
module Authentication
  class Wyngle
    attr_reader :raw_info

    # @param raw_info {OmniAuth::AuthHash} Omniauth Authentication Provider raw info
    # as filled in when +request.env['omniauth.auth']
    #
    # example:
    #
    #    raw_info.provider ... which should be +:wyngle+
    #    raw_info.uid      ... which should be the user id in the provider database
    #    raw_info.info {OmniAuth::AuthHash::InfoHash}
    #       raw_info.info['email']
    #       raw_info.info['gender']
    #       raw_info.info['first_name']
    #       raw_info.info['last_name']
    #       raw_info.info['time_zone']
    #       raw_info.info['address']['address']
    #       raw_info.info['address']['address_expanded']
    #       raw_info.info['address']['region']
    #       raw_info.info['address']['city']
    #       raw_info.info['address']['postcode']
    #       raw_info.info['address']['country']
    #
    def initialize(raw_info)
      @raw_info = raw_info
    end

    def find_or_create_user
      user = User.find_by_auth_provider_and_auth_provider_id raw_info.provider, raw_info.uid
      if user.nil?
        create_user!
      else
        update_user! user
      end
    end

    def create_user!
      User.create! email: raw_info.info['email'], auth_provider: raw_info.provider, auth_provider_id: raw_info.uid, auth_provider_data: raw_info.info
    end

    def update_user! user
      user.email = raw_info.info['email'] unless raw_info.info['email'].blank?
      user.auth_provider_data = raw_info.info
      user.save!
      user
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  serialize :auth_provider_data, OmniAuth::AuthHash::InfoHash

  validates :auth_provider, presence: true
  validates :auth_provider_id, presence: true, uniqueness: {scope: :auth_provider, case_sensitive: false}

  def first_name
    auth_provider_data['first_name']
  end

  def last_name
    auth_provider_data['last_name']
  end

  def phone
    auth_provider_data['phone']
  end

  def gender
    auth_provider_data['gender']
  end

  def address
    auth_provider_data['address']
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user

  helper_method :current_user

  private

  def authenticate_user
    user = current_user
    if user.nil?
      flash[:error] = "You need to log in before you can access this page!"
      redirect_to root_url
    end
  end

  def current_user
    User.find_by_id session[:user_id]
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end

  def settings
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate_user

  # E.g. GET "/auth/failure?message=access_denied&origin=http://localhost:3001/&strategy=wyngle"
  #
  def auth_failure
    strategy = params[:strategy].titleize
    message  = params[:message].humanize
    if params[:message] == 'access_denied'
      flash[:error] = "Sorry, your access via #{strategy} has been denied"
    else
      flash[:error] = "Sorry, but #{strategy} authentication failed with error: #{message}"
    end
    redirect_to root_url
  end

  # We need to locate user and either create him/her and sign him/her in, or
  # just sign him/her in.
  #
  def auth_wyngle_callback
    Rails.logger.debug request.env.inspect
    raw_info = request.env['omniauth.auth']

    wyngle_auth = Authentication::Wyngle.new(raw_info)
    user = wyngle_auth.find_or_create_user
    if user.nil?
      reset_session
      flash[:error] = "Sorry, you can't log in. Why don't you try again?"
      redirect_to root_url
    else
      reset_session
      sign_in(user)
      flash[:success] = "Hello #{user.first_name}, #{user.last_name}!"
      redirect_to dashboard_url
    end
  end

  def sign_out
    reset_session
    flash[:success] = 'Bye!'
    redirect_to root_url
  end

  private

  # @param user {User}
  #
  def sign_in(user)
    session[:user_id] = user.id
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user

  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/index.html.haml
= link_to "Settings", settings_path

%br
= link_to "Sign Out", "/sign_out"

app/views/dashboard/settings.html.haml
%span
  First Name:
  = current_user.first_name
%br

%span
  Last Name:
  = current_user.last_name
%br

%span
  Gender:
  = current_user.gender
%br

%span
  Email:
  = current_user.email
%br

%span
  Phone:
  = current_user.phone
%br
  
%span
  Address:
  = current_user.address['address']
%br

%span
  Address Expanded:
  = current_user.address['address_expanded']
%br

%span
  Region:
  = current_user.address['region']
%br

%span
  City:
  = current_user.address['city']
%br

%span
  Post Code:
  = current_user.address['postcode']
%br

%span
  Country:
  = current_user.address['country']
%br

= link_to "Dashboard", dashboard_path

app/views/layouts/application.html.haml
!!!
%html
  %head>
    %title
      RorEshop
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    - flash.each do |type, message|
      %div{class: "alert #{type}"}
        = message
  = yield

app/views/welcome/index.html.haml
%h1
  Welcome to Ruby On Rails E-Shop
%h2
  This application demonstrates the Log in with Wyngle functionality
%p
  After you log in with Wyngle, you will have access to #{link_to 'the dashboard', dashboard_path} of this application.
  Dashboard is protected and you cannot access it, unless you log in.
%p
  There, on dashboard, you will see that RoR E-Shop has identified you with the help of Wyngle.
  Moreover, you will see a link to #{link_to 'Settings', settings_path}.
  This link is also protected, and you cannot access it unless you log in with Wyngle. On #{link_to 'Settings', settings_path},
  you will see the data that Wyngle has provided for you after you have logged in.
%p
  = link_to "Log In With Wyngle", "/auth/wyngle"